# Generated by Django 4.2.30 on 2026-07-04 12:04

import apps.notifications_center.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('level', models.CharField(choices=[('success', '成功'), ('info', '普通'), ('warning', '警告'), ('error', '错误')], default='info', max_length=20, verbose_name='级别')),
                ('target_path', models.CharField(blank=True, help_text='可选，只允许以 / 开头的站内路径。', max_length=500, validators=[apps.notifications_center.models.validate_internal_path], verbose_name='站内跳转路径')),
                ('audience', models.CharField(choices=[('all_active', '全部启用用户'), ('selected', '指定用户')], default='selected', max_length=20, verbose_name='收件范围')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='发送数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notification_publications', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('recipients', models.ManyToManyField(blank=True, related_name='notification_publications', to=settings.AUTH_USER_MODEL, verbose_name='指定用户')),
            ],
            options={
                'verbose_name': '通知发布记录',
                'verbose_name_plural': '通知发布记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
