# Generated by Django 4.2.30 on 2026-07-04 14:45

import apps.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('avatar', models.ImageField(blank=True, upload_to=apps.blog.models.ImageUploadTo('authors'), verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(blank=True, upload_to=apps.blog.models.ImageUploadTo('covers'), verbose_name='封面图')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content_type', models.CharField(choices=[('html', '富文本'), ('markdown', 'Markdown')], default='html', max_length=20, verbose_name='内容格式')),
                ('content_html', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='富文本内容')),
                ('content_markdown', models.TextField(blank=True, verbose_name='Markdown 内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, verbose_name='排序')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.author', verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-is_top', '-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['slug', 'is_enabled'], name='blog_tag_slug_4f1280_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.blog.models.ImageUploadTo('post_images'), verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='文章')),
            ],
            options={
                'verbose_name': '文章附图',
                'verbose_name_plural': '文章附图',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_enabled'], name='blog_catego_slug_fea7ff_idx'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_author', to=settings.AUTH_USER_MODEL, verbose_name='关联账号'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'status', 'published_at'], name='blog_post_categor_acbd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_top', 'published_at'], name='blog_post_is_top_1d6c73_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['sort_order'], name='blog_post_sort_or_c380b1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug', 'status'], name='blog_post_slug_714acb_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['is_enabled'], name='blog_author_is_enab_db801a_idx'),
        ),
    ]
