# Generated by Django 4.2.30 on 2026-07-04 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('volcano_ark', '火山方舟')], default='volcano_ark', max_length=50, verbose_name='服务商')),
                ('model_id', models.CharField(max_length=200, verbose_name='模型 ID')),
                ('base_url', models.URLField(blank=True, verbose_name='API 地址')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('timeout', models.PositiveIntegerField(default=60, verbose_name='单次调用超时（秒）')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认配置')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='扩展参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'verbose_name_plural': 'AI 模型配置',
                'ordering': ('-is_default', '-is_active', '-created_at'),
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AIGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('video', '视频'), ('voice', '语音'), ('3d_image', '3D 图像')], default='video', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('processing', '生成中'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('image', models.ImageField(blank=True, upload_to='ai_images/%Y/%m/', verbose_name='参考图片')),
                ('extra_params', models.JSONField(blank=True, default=dict, verbose_name='额外参数')),
                ('external_task_id', models.CharField(blank=True, max_length=255, verbose_name='外部任务 ID')),
                ('result_url', models.URLField(blank=True, verbose_name='结果 URL')),
                ('result_file', models.FileField(blank=True, upload_to='ai_results/%Y/%m/', verbose_name='结果文件')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_tasks', to='ai_integration.aimodelconfig', verbose_name='模型配置')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'AI 生成任务',
                'verbose_name_plural': 'AI 生成任务',
                'ordering': ('-created_at',),
            },
        ),
    ]
